export const formatKES = (amount: number) =>
  new Intl.NumberFormat("en-KE", {
    style: "currency",
    currency: "KES",
    currencyDisplay: "symbol",
    maximumFractionDigits: 2,
  }).format(amount);

export const commonBreedsKE: Record<string, string[]> = {
  dog: [
    "Affenpinscher",
    "Afghan Hound",
    "Airedale Terrier",
    "Akita",
    "Alaskan Malamute",
    "American Bulldog",
    "American Cocker Spaniel",
    "American Pit Bull Terrier",
    "American Staffordshire Terrier",
    "Australian Cattle Dog",
    "Australian Shepherd",
    "Basenji",
    "Basset Hound",
    "Beagle",
    "Belgian Malinois",
    "Bernese Mountain Dog",
    "Bichon Frise",
    "Bloodhound",
    "Border Collie",
    "Border Terrier",
    "Boston Terrier",
    "Boxer",
    "Brittany",
    "Brussels Griffon",
    "Bull Terrier",
    "Bullmastiff",
    "Cairn Terrier",
    "Cane Corso",
    "Cavalier King Charles Spaniel",
    "Chesapeake Bay Retriever",
    "Chihuahua",
    "Chinese Crested",
    "Chinese Shar-Pei",
    "Chow Chow",
    "Cocker Spaniel",
    "Collie",
    "Corgi (Pembroke Welsh)",
    "Corgi (Cardigan Welsh)",
    "Dachshund",
    "Dalmatian",
    "Doberman Pinscher",
    "Dogue de Bordeaux",
    "English Bulldog",
    "English Setter",
    "English Springer Spaniel",
    "French Bulldog",
    "German Pinscher",
    "German Shepherd",
    "German Shorthaired Pointer",
    "Golden Retriever",
    "Gordon Setter",
    "Great Dane",
    "Great Pyrenees",
    "Greyhound",
    "Havanese",
    "Husky (Siberian)",
    "Irish Setter",
    "Irish Wolfhound",
    "Italian Greyhound",
    "Jack Russell Terrier",
    "Japanese Chin",
    "Keeshond",
    "Kerry Blue Terrier",
    "Labrador Retriever",
    "Lhasa Apso",
    "Maltese",
    "Mastiff (English)",
    "Miniature Pinscher",
    "Miniature Schnauzer",
    "Newfoundland",
    "Norfolk Terrier",
    "Norwegian Elkhound",
    "Old English Sheepdog",
    "Papillon",
    "Pekingese",
    "Pointer",
    "Pomeranian",
    "Poodle (Standard)",
    "Poodle (Miniature)",
    "Poodle (Toy)",
    "Portuguese Water Dog",
    "Pug",
    "Rhodesian Ridgeback",
    "Rottweiler",
    "Saint Bernard",
    "Samoyed",
    "Schipperke",
    "Scottish Terrier",
    "Shetland Sheepdog",
    "Shiba Inu",
    "Shih Tzu",
    "Staffordshire Bull Terrier",
    "Tibetan Mastiff",
    "Vizsla",
    "Weimaraner",
    "West Highland White Terrier",
    "Whippet",
    "Wire Fox Terrier",
    "Yorkshire Terrier",
    "Local / Mixed Breed",
  ],
  cat: [
    "Abyssinian",
    "American Bobtail",
    "American Curl",
    "American Shorthair",
    "American Wirehair",
    "Balinese",
    "Bengal",
    "Birman",
    "Bombay",
    "British Longhair",
    "British Shorthair",
    "Burmese",
    "Burmilla",
    "Chartreux",
    "Cornish Rex",
    "Devon Rex",
    "Domestic Longhair",
    "Domestic Medium Hair",
    "Domestic Shorthair",
    "Egyptian Mau",
    "Exotic Shorthair",
    "Havana Brown",
    "Himalayan",
    "Japanese Bobtail",
    "Korat",
    "LaPerm",
    "Maine Coon",
    "Manx",
    "Munchkin",
    "Norwegian Forest Cat",
    "Ocicat",
    "Oriental Shorthair",
    "Persian",
    "Ragamuffin",
    "Ragdoll",
    "Russian Blue",
    "Savannah",
    "Scottish Fold",
    "Selkirk Rex",
    "Siamese",
    "Siberian",
    "Singapura",
    "Snowshoe",
    "Somali",
    "Sphynx",
    "Tonkinese",
    "Turkish Angora",
    "Turkish Van",
    "Local / Mixed Breed",
  ],
  bird: [
    "African Grey Parrot",
    "Amazon Parrot",
    "Bald Eagle",
    "Budgerigar (Budgie)",
    "Canary",
    "Chicken (Broiler)",
    "Chicken (Layer)",
    "Chicken (Kienyeji / Indigenous)",
    "Cockatiel",
    "Cockatoo",
    "Conure (Green-Cheeked)",
    "Conure (Sun)",
    "Dove",
    "Duck (Muscovy)",
    "Duck (Pekin)",
    "Duck (Khaki Campbell)",
    "Eclectus Parrot",
    "Emu",
    "Falcon",
    "Finch (Zebra)",
    "Finch (Gouldian)",
    "Flamingo",
    "Goose",
    "Guinea Fowl",
    "Harris Hawk",
    "Hawk",
    "Helmeted Guineafowl",
    "Homing Pigeon",
    "Hyacinth Macaw",
    "Indian Ringneck Parakeet",
    "Kestrel",
    "Lovebird",
    "Macaw (Blue-and-Gold)",
    "Macaw (Scarlet)",
    "Mynah Bird",
    "Ostrich",
    "Owl (Barn)",
    "Owl (Eagle)",
    "Parakeet",
    "Parrotlet",
    "Peacock / Peafowl",
    "Pelican",
    "Pigeon (Racing)",
    "Pigeon (Fancy)",
    "Quail (Common)",
    "Quail (Japanese / Coturnix)",
    "Quaker Parrot",
    "Rosella",
    "Senegal Parrot",
    "Swan",
    "Turkey",
    "Turaco",
    "Weaver Bird",
    "Local / Mixed Breed",
  ],
  rabbit: [
    "American Fuzzy Lop",
    "American Rabbit",
    "Angora (English)",
    "Angora (French)",
    "Angora (Giant)",
    "Belgian Hare",
    "Beveren",
    "Blanc de Hotot",
    "Britannia Petite",
    "Californian",
    "Champagne d'Argent",
    "Checkered Giant",
    "Chinchilla (American)",
    "Chinchilla (Giant)",
    "Cinnamon",
    "Continental Giant",
    "Dutch",
    "Dwarf Hotot",
    "English Lop",
    "English Spot",
    "Flemish Giant",
    "Florida White",
    "French Lop",
    "Harlequin",
    "Havana",
    "Himalayan",
    "Holland Lop",
    "Jersey Wooly",
    "Lionhead",
    "Mini Lop",
    "Mini Rex",
    "Mini Satin",
    "Netherland Dwarf",
    "New Zealand (White)",
    "New Zealand (Red)",
    "Palomino",
    "Polish",
    "Rex",
    "Rhinelander",
    "Satin",
    "Silver Fox",
    "Silver Marten",
    "Standard Chinchilla",
    "Tan",
    "Local / Mixed Breed",
  ],
  hamster: [
    "Campbell's Dwarf",
    "Chinese Hamster",
    "Djungarian (Winter White)",
    "Long-haired Syrian (Teddy Bear)",
    "Roborovski Dwarf",
    "Short-haired Syrian (Golden)",
    "Syrian (Black Bear)",
    "Syrian (Panda Bear)",
    "Local / Mixed Breed",
  ],
  reptile: [
    "African Fat-Tailed Gecko",
    "African Sideneck Turtle",
    "Argentine Black and White Tegu",
    "Ball Python",
    "Bearded Dragon",
    "Blue-Tongued Skink",
    "Boa Constrictor",
    "Box Turtle (Eastern)",
    "Box Turtle (Ornate)",
    "Burmese Python",
    "California Kingsnake",
    "Chameleon (Jackson's)",
    "Chameleon (Panther)",
    "Chameleon (Veiled)",
    "Chinese Water Dragon",
    "Corn Snake",
    "Crested Gecko",
    "Day Gecko (Giant)",
    "Eastern Box Turtle",
    "Gargoyle Gecko",
    "Green Anole",
    "Green Iguana",
    "Green Tree Python",
    "Hermann's Tortoise",
    "Kenyan Sand Boa",
    "King Cobra",
    "Leopard Gecko",
    "Leopard Tortoise",
    "Monitor Lizard (Nile)",
    "Monitor Lizard (Savannah)",
    "Mud Turtle",
    "Nile Crocodile",
    "Painted Turtle",
    "Python (Reticulated)",
    "Python (Royal / Ball)",
    "Rat Snake",
    "Red-Eared Slider",
    "Red-Footed Tortoise",
    "Russian Tortoise",
    "Spiny-Tailed Lizard (Uromastyx)",
    "Sulcata Tortoise",
    "Tokay Gecko",
    "Water Monitor",
    "Western Hognose Snake",
    "Local / Mixed Breed",
  ],
};

export function mpesaStkPushPlaceholder(args: {
  phone: string;
  amount: number;
  accountReference: string;
  description?: string;
}) {
  console.log("[M-Pesa STK Placeholder]", args);
  return Promise.resolve({ ok: true });
}

